server:
  port: 10010
logging:
  level:
    com.young: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址